export const SEO = {
  title: "Notaku - Tu portal de anime",
  description: "Descubre noticias, reseñas y contenido exclusivo sobre anime en Notaku.",
  author: "edard3v",
  img: "https://res.cloudinary.com/dzuo8j1qg/image/upload/v1733991158/edard3v.jpg",
  keywords: [
    "Notaku",
    "anime",
    "manga",
    "noticias de anime",
    "reseñas de anime",
    "temporada anime",
    "estrenos de anime",
    "anime online",
    "weebs",
    "otakus",
    "Astro",
    "web de anime",
  ],
  base_url: "http://localhost:4321/",
};
