export const SEO = {
  title: "Notaku",
  description:
    "Explora el mejor catálogo de animes online. Sinopsis, trailers, recomendaciones y noticias de tus series favoritas de anime. Actualizado constantemente.",
  author: "edard3v",
  img: "https://res.cloudinary.com/dzuo8j1qg/image/upload/v1742375534/notaku/u3d6tzyshtrd2jxk88k1.jpg",
  keywords: [
    "anime",
    "ver anime online",
    "series de anime",
    "anime gratis",
    "estrenos anime",
    "mejores animes",
    "anime en español",
    "temporada anime",
    "recomendaciones de anime",
    "trailers de anime",
    "sinopsis de anime",
    "anime 2025",
    "animes populares",
    "animeverse",
    "edard3v",
  ],
  base_url: "https://notaku-liart.vercel.app",
};
